### PR TITLE
Handle "BOTH" Direction

### PR DESCRIPTION
**Pull request by realaboo**
The targetY should take the mDirection into account.

### CODE REVIEW

**Comment by oliveeyay** [comment]
Hello @realaboo 

Thank you very much for your work! It seems useful! :)

However, I got a couple of things that needs to be kept or modified in order to keep the consistency of the library:
- Could you keep using the enum SwipyRefreshLayoutDirection.TOP/BOTTOM/BOTH
  Duplicating this inside of the SwipyRefreshLayout class can be weird for other developers.
  This way you can pass the BOTH parameter also by xml and/or programmatically
- Could you also update the main app inside of the project for demonstrating that your modification actually works (adding the BOTH mode to it for example). It helps us testing the modification on real devices.
- I did not find a way to test the BOTH direction (I tried not to set any direction, but by default it uses the TOP)
- On the README file, don't add that it has been forked from another repository because when we will merge it, it will appear on our repo also ^^
  Also, don't hesitate to add yourself to the Credits section (Something like "Thank you <name> for the pull requests" or "Pull requests by <name>" after the developer section)

Don't hesitate to contact me for any question.
I could merge any time in the week when the modification are done and publish to the maven repo an updated version.

Thanks again.

Cheers,

Olivier

**Comment by realaboo** [comment]
Please review the new commit.

**Comment by oliveeyay** [comment]
Hello @realaboo 

Thanks for the new commit.
I will try to review it today, otherwise I'm gonna review it Monday (we are in PST timezone by the way).

Cheers,

Olivier

**Comment by oliveeyay** [comment]
Hello @realaboo 

Thank you very much for your work, it's perfect now.
I am going to merge and publish a new version on the maven repo.
I will update this thread as soon as the new version is up.

Cheers,

Olivier

**Comment by oliveeyay** [comment]
New version 1.1.0 published.
You can see the new README file to fetch the new version through gradle.

Cheers,

Olivier

**Pull request merged**
